language: php 

env:
   global:
     - COMMIT=${TRAVIS_COMMIT::8}

services:
    - docker

install: 
    - echo "install nothing"

script:
    - echo "no tests"

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=rmortale/wildfly-mysql
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
